image: node:8.9

services:
- name: mongo:3.4.10
  alias: mymongo

variables:
  DB_URI: "mongodb://mymongo:27017/rblog"

stages:
  - test

api_test:
  stage: test
  script:
    - cd server
    - npm install
    - npm run test