image: node:8.9

services:
- name: mongo:3.4.10
  alias: mymongo

variables:
  DB_URI: "mongodb://mymongo/blog"
  PORT: "1000"
  DEBUG: "*,-express:*,-morgan,-send,-body-parser:*"

stages:
  - test

api_test:
  stage: test
  script:
    - cd server
    - npm install
    - npm run test