export const REQUEST = 'CM/REQUEST'
export const REQUEST_START = 'CM/REQUEST_START'
export const REQUEST_FINISHED = 'CM/REQUEST_FINISHED'

export const SET_ERROR = 'CM/SET_ERROR'
export const SET_SUCCESS = 'CM/SET_SUCCESS'
export const CLEAR_ALERT = 'CM/CLEAR_ALERT'

export const SET_IDENTITY = 'CM/SET_IDENTITY'
export const LOAD_IDENTITY = 'CM/LOAD_IDENTITY'
export const CLEAR_IDENTITY = 'CM/CLEAR_IDENTITY'
